### PR TITLE
Fix Bind Args

### LINKED ISSUE #39: Fix Bind Parameters
It seems that binded methods aren't able to receive the passed args

### PR DESCRIPTION
**Pull request by SentryMan**
Checking size of the pointer was not the way to do it.

- fix bind args

resolves #39

### CODE REVIEW

File: avaje-webview/src/main/java/io/avaje/webview/DWebView.java [hunk 1]
```diff
@@ -369,6 +378,36 @@ public String version() {
...
+
+  /**
+   * Checks the environment to ensure compatibility with the current platform.
+   *
+   * <p>This method performs platform-specific checks to verify that the application is running in a
+   * supported environment.
+   *
+   * @throws UnsupportedOperationException if the environment does not meet the required conditions.
+   */
+  private void checkEnvironment() {
```
Comment (rbygrave) [inline avaje-webview/src/main/java/io/avaje/webview/DWebView.java]: This doesn't work with native image, it needs to be:

```
  private void checkEnvironment() {
    if (OS_DISTRIBUTION == MACOS) {
      if (async || isMainThread() || MacOSHelper.startedOnFirstThread()) {
        return;
      }
      String extra = isMainThread() ? MACOS_RELOAD : MACOS_DEVELOPER_ERROR;
      throw new UnsupportedOperationException(ERROR_NO_XSTART_ON_FIRST_THREAD + extra);
    }
  }
```
... also note that currently I don't think async will work on MacOS.

Comment (SentryMan) [reply avaje-webview/src/main/java/io/avaje/webview/DWebView.java]: let's put a pin in this and add it later

**Comment by SentryMan** [comment]
ah CTRL-C, gimme a sec

**Comment by rbygrave** [comment]
I've got the change that fixes CTRL-C.  Shall I push it?

**Comment by SentryMan** [comment]
you beat me to it then, go nuts

**Comment by rbygrave** [comment]
Ok, I've pushed that change. Not 100% sure on it.  I'm actually wondering that the alternative was along the lines that there was missing reachability meta data?  What was your approach to the CTRL-C fix? Was it better than adding the shutdown method?

**Comment by SentryMan** [comment]
hmm no I still get it with that, gimme a second

**Comment by SentryMan** [comment]
it seems that even if I revert the async changes CTRL-C doesn't work

**Comment by rbygrave** [comment]
> CTRL-C doesn't work

It was working for the https://github.com/avaje/avaje-webview/blob/main/examples/htmx-jex-bootstrap/src/main/java/io/example/Main.java ... on MacOS compiled to native image.

How were you testing it @SentryMan  ?

**Comment by rbygrave** [comment]
Ah, think it's missing some reflection meta data to run that example, missing reflection meta like:

```json
    {
      "type": {
        "lambda": {
          "declaringClass": "io.avaje.webview.DWebView",
          "interfaces": [
            "io.avaje.webview.DWebView$BindCallback"
          ]
        }
      },
      "methods": [
        {
          "name": "invoke",
          "parameterTypes": [
            "long",
            "java.lang.foreign.MemorySegment"
          ]
        }
      ]
    }
```

I'm looking at running this example as a native exe now ...

**Comment by rbygrave** [comment]
`hello-world-jex ` is still actually busted for native image in the main branch
